export const LocationsActionTypes = {
  FETCH:                  '@@location/FETCH',
  FETCH_SUCCESS:          '@@location/FETCH_SUCCESS',
  FETCH_ERROR:            '@@location/FETCH_ERROR',
  INSERT_INPUT_ON_CHANGE: '@@location/INSERT_INPUT_ON_CHANGE',
  INSERT:                 '@@location/INSERT',
  INSERT_SUCCESS:         '@@location/INSERT_SUCCESS',
  INSERT_ERROR:           '@@location/INSERT_ERROR',
  UPDATE:                 '@@location/UPDATE',
  UPDATE_SUCCESS:         '@@location/UPDATE_SUCCESS',
  UPDATE_ERROR:           '@@location/UPDATE_ERROR',
  DELETE:                 '@@location/DELETE',
  DELETE_SUCCESS:         '@@location/DELETE_SUCCESS',
  DELETE_ERROR:           '@@location/DELETE_ERROR',
  CLEAR_API_CALL_STATUS:  '@@location/CLEAR_API_CALL_STATUS',
};
